
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
/**
 * Model Invitation
 * 
 */
export type Invitation = Prisma.InvitationModel
/**
 * Model Membership
 * 
 */
export type Membership = Prisma.MembershipModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Sprint
 * 
 */
export type Sprint = Prisma.SprintModel
/**
 * Model Task
 * 
 */
export type Task = Prisma.TaskModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Workspace
 * 
 */
export type Workspace = Prisma.WorkspaceModel
