
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AuditActions = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  INVITE_SENT: 'INVITE_SENT',
  INVITE_ACCEPTED: 'INVITE_ACCEPTED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_ASSIGNEE_CHANGED: 'TASK_ASSIGNEE_CHANGED',
  PROJECT_RENAMED: 'PROJECT_RENAMED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
} as const

export type AuditActions = (typeof AuditActions)[keyof typeof AuditActions]


export const InvitationStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED'
} as const

export type InvitationStatus = (typeof InvitationStatus)[keyof typeof InvitationStatus]


export const MembershipStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REMOVED: 'REMOVED'
} as const

export type MembershipStatus = (typeof MembershipStatus)[keyof typeof MembershipStatus]


export const NotificationType = {
  WORKSPACE_DELETED: 'WORKSPACE_DELETED',
  WORKSPACE_INVITE: 'WORKSPACE_INVITE',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  WORKSPACE_NOTIFICATION: 'WORKSPACE_NOTIFICATION'
} as const

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType]


export const PaymentStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const PlatformRole = {
  USER: 'USER',
  SYSADMIN: 'SYSADMIN'
} as const

export type PlatformRole = (typeof PlatformRole)[keyof typeof PlatformRole]


export const Role = {
  MEMBER: 'MEMBER',
  OWNER: 'OWNER',
  ADMIN: 'ADMIN'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const SprintColor = {
  LAVENDER: 'LAVENDER',
  MINT: 'MINT',
  PEACH: 'PEACH',
  BABY_BLUE: 'BABY_BLUE',
  BLUSH: 'BLUSH',
  LILAC: 'LILAC',
  APRICOT: 'APRICOT',
  POWDER: 'POWDER',
  SKY: 'SKY'
} as const

export type SprintColor = (typeof SprintColor)[keyof typeof SprintColor]


export const SprintStatus = {
  PLANNED: 'PLANNED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type SprintStatus = (typeof SprintStatus)[keyof typeof SprintStatus]


export const Tariff = {
  FREE: 'FREE',
  PRO: 'PRO',
  BUSINESS: 'BUSINESS'
} as const

export type Tariff = (typeof Tariff)[keyof typeof Tariff]


export const TaskPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
} as const

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority]


export const TaskStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  BLOCKED: 'BLOCKED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]


export const TaskType = {
  TASK: 'TASK',
  BUG: 'BUG',
  STORY: 'STORY',
  EPIC: 'EPIC'
} as const

export type TaskType = (typeof TaskType)[keyof typeof TaskType]
