
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Workspace` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Workspace
 * 
 */
export type WorkspaceModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkspacePayload>

export type AggregateWorkspace = {
  _count: WorkspaceCountAggregateOutputType | null
  _avg: WorkspaceAvgAggregateOutputType | null
  _sum: WorkspaceSumAggregateOutputType | null
  _min: WorkspaceMinAggregateOutputType | null
  _max: WorkspaceMaxAggregateOutputType | null
}

export type WorkspaceAvgAggregateOutputType = {
  id: number | null
}

export type WorkspaceSumAggregateOutputType = {
  id: number | null
}

export type WorkspaceMinAggregateOutputType = {
  id: number | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
  description: string | null
  ownerId: string | null
  avatarUrl: string | null
}

export type WorkspaceMaxAggregateOutputType = {
  id: number | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
  description: string | null
  ownerId: string | null
  avatarUrl: string | null
}

export type WorkspaceCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  updatedAt: number
  description: number
  ownerId: number
  avatarUrl: number
  _all: number
}


export type WorkspaceAvgAggregateInputType = {
  id?: true
}

export type WorkspaceSumAggregateInputType = {
  id?: true
}

export type WorkspaceMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  description?: true
  ownerId?: true
  avatarUrl?: true
}

export type WorkspaceMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  description?: true
  ownerId?: true
  avatarUrl?: true
}

export type WorkspaceCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  description?: true
  ownerId?: true
  avatarUrl?: true
  _all?: true
}

export type WorkspaceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Workspace to aggregate.
   */
  where?: Prisma.WorkspaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workspaces to fetch.
   */
  orderBy?: Prisma.WorkspaceOrderByWithRelationInput | Prisma.WorkspaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkspaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workspaces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workspaces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Workspaces
  **/
  _count?: true | WorkspaceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkspaceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkspaceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkspaceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkspaceMaxAggregateInputType
}

export type GetWorkspaceAggregateType<T extends WorkspaceAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkspace]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkspace[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkspace[P]>
}




export type WorkspaceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkspaceWhereInput
  orderBy?: Prisma.WorkspaceOrderByWithAggregationInput | Prisma.WorkspaceOrderByWithAggregationInput[]
  by: Prisma.WorkspaceScalarFieldEnum[] | Prisma.WorkspaceScalarFieldEnum
  having?: Prisma.WorkspaceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkspaceCountAggregateInputType | true
  _avg?: WorkspaceAvgAggregateInputType
  _sum?: WorkspaceSumAggregateInputType
  _min?: WorkspaceMinAggregateInputType
  _max?: WorkspaceMaxAggregateInputType
}

export type WorkspaceGroupByOutputType = {
  id: number
  name: string
  createdAt: Date
  updatedAt: Date
  description: string | null
  ownerId: string | null
  avatarUrl: string | null
  _count: WorkspaceCountAggregateOutputType | null
  _avg: WorkspaceAvgAggregateOutputType | null
  _sum: WorkspaceSumAggregateOutputType | null
  _min: WorkspaceMinAggregateOutputType | null
  _max: WorkspaceMaxAggregateOutputType | null
}

type GetWorkspaceGroupByPayload<T extends WorkspaceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkspaceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkspaceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkspaceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkspaceGroupByOutputType[P]>
      }
    >
  >



export type WorkspaceWhereInput = {
  AND?: Prisma.WorkspaceWhereInput | Prisma.WorkspaceWhereInput[]
  OR?: Prisma.WorkspaceWhereInput[]
  NOT?: Prisma.WorkspaceWhereInput | Prisma.WorkspaceWhereInput[]
  id?: Prisma.IntFilter<"Workspace"> | number
  name?: Prisma.StringFilter<"Workspace"> | string
  createdAt?: Prisma.DateTimeFilter<"Workspace"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Workspace"> | Date | string
  description?: Prisma.StringNullableFilter<"Workspace"> | string | null
  ownerId?: Prisma.StringNullableFilter<"Workspace"> | string | null
  avatarUrl?: Prisma.StringNullableFilter<"Workspace"> | string | null
  AuditLog?: Prisma.AuditLogListRelationFilter
  Invitation?: Prisma.InvitationListRelationFilter
  Membership?: Prisma.MembershipListRelationFilter
  Notification?: Prisma.NotificationListRelationFilter
  Project?: Prisma.ProjectListRelationFilter
  User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type WorkspaceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  avatarUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  AuditLog?: Prisma.AuditLogOrderByRelationAggregateInput
  Invitation?: Prisma.InvitationOrderByRelationAggregateInput
  Membership?: Prisma.MembershipOrderByRelationAggregateInput
  Notification?: Prisma.NotificationOrderByRelationAggregateInput
  Project?: Prisma.ProjectOrderByRelationAggregateInput
  User?: Prisma.UserOrderByWithRelationInput
}

export type WorkspaceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.WorkspaceWhereInput | Prisma.WorkspaceWhereInput[]
  OR?: Prisma.WorkspaceWhereInput[]
  NOT?: Prisma.WorkspaceWhereInput | Prisma.WorkspaceWhereInput[]
  name?: Prisma.StringFilter<"Workspace"> | string
  createdAt?: Prisma.DateTimeFilter<"Workspace"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Workspace"> | Date | string
  description?: Prisma.StringNullableFilter<"Workspace"> | string | null
  ownerId?: Prisma.StringNullableFilter<"Workspace"> | string | null
  avatarUrl?: Prisma.StringNullableFilter<"Workspace"> | string | null
  AuditLog?: Prisma.AuditLogListRelationFilter
  Invitation?: Prisma.InvitationListRelationFilter
  Membership?: Prisma.MembershipListRelationFilter
  Notification?: Prisma.NotificationListRelationFilter
  Project?: Prisma.ProjectListRelationFilter
  User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type WorkspaceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  avatarUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.WorkspaceCountOrderByAggregateInput
  _avg?: Prisma.WorkspaceAvgOrderByAggregateInput
  _max?: Prisma.WorkspaceMaxOrderByAggregateInput
  _min?: Prisma.WorkspaceMinOrderByAggregateInput
  _sum?: Prisma.WorkspaceSumOrderByAggregateInput
}

export type WorkspaceScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkspaceScalarWhereWithAggregatesInput | Prisma.WorkspaceScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkspaceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkspaceScalarWhereWithAggregatesInput | Prisma.WorkspaceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Workspace"> | number
  name?: Prisma.StringWithAggregatesFilter<"Workspace"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Workspace"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Workspace"> | Date | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Workspace"> | string | null
  ownerId?: Prisma.StringNullableWithAggregatesFilter<"Workspace"> | string | null
  avatarUrl?: Prisma.StringNullableWithAggregatesFilter<"Workspace"> | string | null
}

export type WorkspaceCreateInput = {
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectCreateNestedManyWithoutWorkspaceInput
  User?: Prisma.UserCreateNestedOneWithoutWorkspaceInput
}

export type WorkspaceUncheckedCreateInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  ownerId?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogUncheckedCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationUncheckedCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipUncheckedCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationUncheckedCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUpdateManyWithoutWorkspaceNestedInput
  User?: Prisma.UserUpdateOneWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUncheckedUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUncheckedUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceCreateManyInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  ownerId?: string | null
  avatarUrl?: string | null
}

export type WorkspaceUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkspaceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkspaceNullableScalarRelationFilter = {
  is?: Prisma.WorkspaceWhereInput | null
  isNot?: Prisma.WorkspaceWhereInput | null
}

export type WorkspaceScalarRelationFilter = {
  is?: Prisma.WorkspaceWhereInput
  isNot?: Prisma.WorkspaceWhereInput
}

export type WorkspaceListRelationFilter = {
  every?: Prisma.WorkspaceWhereInput
  some?: Prisma.WorkspaceWhereInput
  none?: Prisma.WorkspaceWhereInput
}

export type WorkspaceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkspaceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  avatarUrl?: Prisma.SortOrder
}

export type WorkspaceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type WorkspaceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  avatarUrl?: Prisma.SortOrder
}

export type WorkspaceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  avatarUrl?: Prisma.SortOrder
}

export type WorkspaceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type WorkspaceCreateNestedOneWithoutAuditLogInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutAuditLogInput, Prisma.WorkspaceUncheckedCreateWithoutAuditLogInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutAuditLogInput
  connect?: Prisma.WorkspaceWhereUniqueInput
}

export type WorkspaceUpdateOneWithoutAuditLogNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutAuditLogInput, Prisma.WorkspaceUncheckedCreateWithoutAuditLogInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutAuditLogInput
  upsert?: Prisma.WorkspaceUpsertWithoutAuditLogInput
  disconnect?: Prisma.WorkspaceWhereInput | boolean
  delete?: Prisma.WorkspaceWhereInput | boolean
  connect?: Prisma.WorkspaceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkspaceUpdateToOneWithWhereWithoutAuditLogInput, Prisma.WorkspaceUpdateWithoutAuditLogInput>, Prisma.WorkspaceUncheckedUpdateWithoutAuditLogInput>
}

export type WorkspaceCreateNestedOneWithoutInvitationInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutInvitationInput, Prisma.WorkspaceUncheckedCreateWithoutInvitationInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutInvitationInput
  connect?: Prisma.WorkspaceWhereUniqueInput
}

export type WorkspaceUpdateOneRequiredWithoutInvitationNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutInvitationInput, Prisma.WorkspaceUncheckedCreateWithoutInvitationInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutInvitationInput
  upsert?: Prisma.WorkspaceUpsertWithoutInvitationInput
  connect?: Prisma.WorkspaceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkspaceUpdateToOneWithWhereWithoutInvitationInput, Prisma.WorkspaceUpdateWithoutInvitationInput>, Prisma.WorkspaceUncheckedUpdateWithoutInvitationInput>
}

export type WorkspaceCreateNestedOneWithoutMembershipInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutMembershipInput, Prisma.WorkspaceUncheckedCreateWithoutMembershipInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutMembershipInput
  connect?: Prisma.WorkspaceWhereUniqueInput
}

export type WorkspaceUpdateOneRequiredWithoutMembershipNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutMembershipInput, Prisma.WorkspaceUncheckedCreateWithoutMembershipInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutMembershipInput
  upsert?: Prisma.WorkspaceUpsertWithoutMembershipInput
  connect?: Prisma.WorkspaceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkspaceUpdateToOneWithWhereWithoutMembershipInput, Prisma.WorkspaceUpdateWithoutMembershipInput>, Prisma.WorkspaceUncheckedUpdateWithoutMembershipInput>
}

export type WorkspaceCreateNestedOneWithoutNotificationInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutNotificationInput, Prisma.WorkspaceUncheckedCreateWithoutNotificationInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutNotificationInput
  connect?: Prisma.WorkspaceWhereUniqueInput
}

export type WorkspaceUpdateOneWithoutNotificationNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutNotificationInput, Prisma.WorkspaceUncheckedCreateWithoutNotificationInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutNotificationInput
  upsert?: Prisma.WorkspaceUpsertWithoutNotificationInput
  disconnect?: Prisma.WorkspaceWhereInput | boolean
  delete?: Prisma.WorkspaceWhereInput | boolean
  connect?: Prisma.WorkspaceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkspaceUpdateToOneWithWhereWithoutNotificationInput, Prisma.WorkspaceUpdateWithoutNotificationInput>, Prisma.WorkspaceUncheckedUpdateWithoutNotificationInput>
}

export type WorkspaceCreateNestedOneWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutProjectInput, Prisma.WorkspaceUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutProjectInput
  connect?: Prisma.WorkspaceWhereUniqueInput
}

export type WorkspaceUpdateOneRequiredWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutProjectInput, Prisma.WorkspaceUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutProjectInput
  upsert?: Prisma.WorkspaceUpsertWithoutProjectInput
  connect?: Prisma.WorkspaceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkspaceUpdateToOneWithWhereWithoutProjectInput, Prisma.WorkspaceUpdateWithoutProjectInput>, Prisma.WorkspaceUncheckedUpdateWithoutProjectInput>
}

export type WorkspaceCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutUserInput, Prisma.WorkspaceUncheckedCreateWithoutUserInput> | Prisma.WorkspaceCreateWithoutUserInput[] | Prisma.WorkspaceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutUserInput | Prisma.WorkspaceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkspaceCreateManyUserInputEnvelope
  connect?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
}

export type WorkspaceUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutUserInput, Prisma.WorkspaceUncheckedCreateWithoutUserInput> | Prisma.WorkspaceCreateWithoutUserInput[] | Prisma.WorkspaceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutUserInput | Prisma.WorkspaceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkspaceCreateManyUserInputEnvelope
  connect?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
}

export type WorkspaceUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutUserInput, Prisma.WorkspaceUncheckedCreateWithoutUserInput> | Prisma.WorkspaceCreateWithoutUserInput[] | Prisma.WorkspaceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutUserInput | Prisma.WorkspaceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkspaceUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkspaceCreateManyUserInputEnvelope
  set?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  delete?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  connect?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  update?: Prisma.WorkspaceUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkspaceUpdateManyWithWhereWithoutUserInput | Prisma.WorkspaceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkspaceScalarWhereInput | Prisma.WorkspaceScalarWhereInput[]
}

export type WorkspaceUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceCreateWithoutUserInput, Prisma.WorkspaceUncheckedCreateWithoutUserInput> | Prisma.WorkspaceCreateWithoutUserInput[] | Prisma.WorkspaceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceCreateOrConnectWithoutUserInput | Prisma.WorkspaceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkspaceUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkspaceCreateManyUserInputEnvelope
  set?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  delete?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  connect?: Prisma.WorkspaceWhereUniqueInput | Prisma.WorkspaceWhereUniqueInput[]
  update?: Prisma.WorkspaceUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkspaceUpdateManyWithWhereWithoutUserInput | Prisma.WorkspaceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkspaceScalarWhereInput | Prisma.WorkspaceScalarWhereInput[]
}

export type WorkspaceCreateWithoutAuditLogInput = {
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  Invitation?: Prisma.InvitationCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectCreateNestedManyWithoutWorkspaceInput
  User?: Prisma.UserCreateNestedOneWithoutWorkspaceInput
}

export type WorkspaceUncheckedCreateWithoutAuditLogInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  ownerId?: string | null
  avatarUrl?: string | null
  Invitation?: Prisma.InvitationUncheckedCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipUncheckedCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationUncheckedCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceCreateOrConnectWithoutAuditLogInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutAuditLogInput, Prisma.WorkspaceUncheckedCreateWithoutAuditLogInput>
}

export type WorkspaceUpsertWithoutAuditLogInput = {
  update: Prisma.XOR<Prisma.WorkspaceUpdateWithoutAuditLogInput, Prisma.WorkspaceUncheckedUpdateWithoutAuditLogInput>
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutAuditLogInput, Prisma.WorkspaceUncheckedCreateWithoutAuditLogInput>
  where?: Prisma.WorkspaceWhereInput
}

export type WorkspaceUpdateToOneWithWhereWithoutAuditLogInput = {
  where?: Prisma.WorkspaceWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUpdateWithoutAuditLogInput, Prisma.WorkspaceUncheckedUpdateWithoutAuditLogInput>
}

export type WorkspaceUpdateWithoutAuditLogInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Invitation?: Prisma.InvitationUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUpdateManyWithoutWorkspaceNestedInput
  User?: Prisma.UserUpdateOneWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateWithoutAuditLogInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Invitation?: Prisma.InvitationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUncheckedUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceCreateWithoutInvitationInput = {
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectCreateNestedManyWithoutWorkspaceInput
  User?: Prisma.UserCreateNestedOneWithoutWorkspaceInput
}

export type WorkspaceUncheckedCreateWithoutInvitationInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  ownerId?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogUncheckedCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipUncheckedCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationUncheckedCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceCreateOrConnectWithoutInvitationInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutInvitationInput, Prisma.WorkspaceUncheckedCreateWithoutInvitationInput>
}

export type WorkspaceUpsertWithoutInvitationInput = {
  update: Prisma.XOR<Prisma.WorkspaceUpdateWithoutInvitationInput, Prisma.WorkspaceUncheckedUpdateWithoutInvitationInput>
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutInvitationInput, Prisma.WorkspaceUncheckedCreateWithoutInvitationInput>
  where?: Prisma.WorkspaceWhereInput
}

export type WorkspaceUpdateToOneWithWhereWithoutInvitationInput = {
  where?: Prisma.WorkspaceWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUpdateWithoutInvitationInput, Prisma.WorkspaceUncheckedUpdateWithoutInvitationInput>
}

export type WorkspaceUpdateWithoutInvitationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUpdateManyWithoutWorkspaceNestedInput
  User?: Prisma.UserUpdateOneWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateWithoutInvitationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUncheckedUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUncheckedUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceCreateWithoutMembershipInput = {
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectCreateNestedManyWithoutWorkspaceInput
  User?: Prisma.UserCreateNestedOneWithoutWorkspaceInput
}

export type WorkspaceUncheckedCreateWithoutMembershipInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  ownerId?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogUncheckedCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationUncheckedCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationUncheckedCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceCreateOrConnectWithoutMembershipInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutMembershipInput, Prisma.WorkspaceUncheckedCreateWithoutMembershipInput>
}

export type WorkspaceUpsertWithoutMembershipInput = {
  update: Prisma.XOR<Prisma.WorkspaceUpdateWithoutMembershipInput, Prisma.WorkspaceUncheckedUpdateWithoutMembershipInput>
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutMembershipInput, Prisma.WorkspaceUncheckedCreateWithoutMembershipInput>
  where?: Prisma.WorkspaceWhereInput
}

export type WorkspaceUpdateToOneWithWhereWithoutMembershipInput = {
  where?: Prisma.WorkspaceWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUpdateWithoutMembershipInput, Prisma.WorkspaceUncheckedUpdateWithoutMembershipInput>
}

export type WorkspaceUpdateWithoutMembershipInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUpdateManyWithoutWorkspaceNestedInput
  User?: Prisma.UserUpdateOneWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateWithoutMembershipInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUncheckedUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceCreateWithoutNotificationInput = {
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectCreateNestedManyWithoutWorkspaceInput
  User?: Prisma.UserCreateNestedOneWithoutWorkspaceInput
}

export type WorkspaceUncheckedCreateWithoutNotificationInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  ownerId?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogUncheckedCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationUncheckedCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipUncheckedCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceCreateOrConnectWithoutNotificationInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutNotificationInput, Prisma.WorkspaceUncheckedCreateWithoutNotificationInput>
}

export type WorkspaceUpsertWithoutNotificationInput = {
  update: Prisma.XOR<Prisma.WorkspaceUpdateWithoutNotificationInput, Prisma.WorkspaceUncheckedUpdateWithoutNotificationInput>
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutNotificationInput, Prisma.WorkspaceUncheckedCreateWithoutNotificationInput>
  where?: Prisma.WorkspaceWhereInput
}

export type WorkspaceUpdateToOneWithWhereWithoutNotificationInput = {
  where?: Prisma.WorkspaceWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUpdateWithoutNotificationInput, Prisma.WorkspaceUncheckedUpdateWithoutNotificationInput>
}

export type WorkspaceUpdateWithoutNotificationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUpdateManyWithoutWorkspaceNestedInput
  User?: Prisma.UserUpdateOneWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateWithoutNotificationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUncheckedUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUncheckedUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceCreateWithoutProjectInput = {
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationCreateNestedManyWithoutWorkspaceInput
  User?: Prisma.UserCreateNestedOneWithoutWorkspaceInput
}

export type WorkspaceUncheckedCreateWithoutProjectInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  ownerId?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogUncheckedCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationUncheckedCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipUncheckedCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationUncheckedCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceCreateOrConnectWithoutProjectInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutProjectInput, Prisma.WorkspaceUncheckedCreateWithoutProjectInput>
}

export type WorkspaceUpsertWithoutProjectInput = {
  update: Prisma.XOR<Prisma.WorkspaceUpdateWithoutProjectInput, Prisma.WorkspaceUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutProjectInput, Prisma.WorkspaceUncheckedCreateWithoutProjectInput>
  where?: Prisma.WorkspaceWhereInput
}

export type WorkspaceUpdateToOneWithWhereWithoutProjectInput = {
  where?: Prisma.WorkspaceWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUpdateWithoutProjectInput, Prisma.WorkspaceUncheckedUpdateWithoutProjectInput>
}

export type WorkspaceUpdateWithoutProjectInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUpdateManyWithoutWorkspaceNestedInput
  User?: Prisma.UserUpdateOneWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUncheckedUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUncheckedUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUncheckedUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceCreateWithoutUserInput = {
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceUncheckedCreateWithoutUserInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
  AuditLog?: Prisma.AuditLogUncheckedCreateNestedManyWithoutWorkspaceInput
  Invitation?: Prisma.InvitationUncheckedCreateNestedManyWithoutWorkspaceInput
  Membership?: Prisma.MembershipUncheckedCreateNestedManyWithoutWorkspaceInput
  Notification?: Prisma.NotificationUncheckedCreateNestedManyWithoutWorkspaceInput
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutWorkspaceInput
}

export type WorkspaceCreateOrConnectWithoutUserInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutUserInput, Prisma.WorkspaceUncheckedCreateWithoutUserInput>
}

export type WorkspaceCreateManyUserInputEnvelope = {
  data: Prisma.WorkspaceCreateManyUserInput | Prisma.WorkspaceCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type WorkspaceUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkspaceUpdateWithoutUserInput, Prisma.WorkspaceUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.WorkspaceCreateWithoutUserInput, Prisma.WorkspaceUncheckedCreateWithoutUserInput>
}

export type WorkspaceUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkspaceWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkspaceUpdateWithoutUserInput, Prisma.WorkspaceUncheckedUpdateWithoutUserInput>
}

export type WorkspaceUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.WorkspaceScalarWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUpdateManyMutationInput, Prisma.WorkspaceUncheckedUpdateManyWithoutUserInput>
}

export type WorkspaceScalarWhereInput = {
  AND?: Prisma.WorkspaceScalarWhereInput | Prisma.WorkspaceScalarWhereInput[]
  OR?: Prisma.WorkspaceScalarWhereInput[]
  NOT?: Prisma.WorkspaceScalarWhereInput | Prisma.WorkspaceScalarWhereInput[]
  id?: Prisma.IntFilter<"Workspace"> | number
  name?: Prisma.StringFilter<"Workspace"> | string
  createdAt?: Prisma.DateTimeFilter<"Workspace"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Workspace"> | Date | string
  description?: Prisma.StringNullableFilter<"Workspace"> | string | null
  ownerId?: Prisma.StringNullableFilter<"Workspace"> | string | null
  avatarUrl?: Prisma.StringNullableFilter<"Workspace"> | string | null
}

export type WorkspaceCreateManyUserInput = {
  id?: number
  name: string
  createdAt?: Date | string
  updatedAt: Date | string
  description?: string | null
  avatarUrl?: string | null
}

export type WorkspaceUpdateWithoutUserInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  AuditLog?: Prisma.AuditLogUncheckedUpdateManyWithoutWorkspaceNestedInput
  Invitation?: Prisma.InvitationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Membership?: Prisma.MembershipUncheckedUpdateManyWithoutWorkspaceNestedInput
  Notification?: Prisma.NotificationUncheckedUpdateManyWithoutWorkspaceNestedInput
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutWorkspaceNestedInput
}

export type WorkspaceUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  avatarUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type WorkspaceCountOutputType
 */

export type WorkspaceCountOutputType = {
  AuditLog: number
  Invitation: number
  Membership: number
  Notification: number
  Project: number
}

export type WorkspaceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  AuditLog?: boolean | WorkspaceCountOutputTypeCountAuditLogArgs
  Invitation?: boolean | WorkspaceCountOutputTypeCountInvitationArgs
  Membership?: boolean | WorkspaceCountOutputTypeCountMembershipArgs
  Notification?: boolean | WorkspaceCountOutputTypeCountNotificationArgs
  Project?: boolean | WorkspaceCountOutputTypeCountProjectArgs
}

/**
 * WorkspaceCountOutputType without action
 */
export type WorkspaceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceCountOutputType
   */
  select?: Prisma.WorkspaceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WorkspaceCountOutputType without action
 */
export type WorkspaceCountOutputTypeCountAuditLogArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuditLogWhereInput
}

/**
 * WorkspaceCountOutputType without action
 */
export type WorkspaceCountOutputTypeCountInvitationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InvitationWhereInput
}

/**
 * WorkspaceCountOutputType without action
 */
export type WorkspaceCountOutputTypeCountMembershipArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MembershipWhereInput
}

/**
 * WorkspaceCountOutputType without action
 */
export type WorkspaceCountOutputTypeCountNotificationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationWhereInput
}

/**
 * WorkspaceCountOutputType without action
 */
export type WorkspaceCountOutputTypeCountProjectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
}


export type WorkspaceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
  ownerId?: boolean
  avatarUrl?: boolean
  AuditLog?: boolean | Prisma.Workspace$AuditLogArgs<ExtArgs>
  Invitation?: boolean | Prisma.Workspace$InvitationArgs<ExtArgs>
  Membership?: boolean | Prisma.Workspace$MembershipArgs<ExtArgs>
  Notification?: boolean | Prisma.Workspace$NotificationArgs<ExtArgs>
  Project?: boolean | Prisma.Workspace$ProjectArgs<ExtArgs>
  User?: boolean | Prisma.Workspace$UserArgs<ExtArgs>
  _count?: boolean | Prisma.WorkspaceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workspace"]>

export type WorkspaceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
  ownerId?: boolean
  avatarUrl?: boolean
  User?: boolean | Prisma.Workspace$UserArgs<ExtArgs>
}, ExtArgs["result"]["workspace"]>

export type WorkspaceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
  ownerId?: boolean
  avatarUrl?: boolean
  User?: boolean | Prisma.Workspace$UserArgs<ExtArgs>
}, ExtArgs["result"]["workspace"]>

export type WorkspaceSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
  ownerId?: boolean
  avatarUrl?: boolean
}

export type WorkspaceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "updatedAt" | "description" | "ownerId" | "avatarUrl", ExtArgs["result"]["workspace"]>
export type WorkspaceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  AuditLog?: boolean | Prisma.Workspace$AuditLogArgs<ExtArgs>
  Invitation?: boolean | Prisma.Workspace$InvitationArgs<ExtArgs>
  Membership?: boolean | Prisma.Workspace$MembershipArgs<ExtArgs>
  Notification?: boolean | Prisma.Workspace$NotificationArgs<ExtArgs>
  Project?: boolean | Prisma.Workspace$ProjectArgs<ExtArgs>
  User?: boolean | Prisma.Workspace$UserArgs<ExtArgs>
  _count?: boolean | Prisma.WorkspaceCountOutputTypeDefaultArgs<ExtArgs>
}
export type WorkspaceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.Workspace$UserArgs<ExtArgs>
}
export type WorkspaceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.Workspace$UserArgs<ExtArgs>
}

export type $WorkspacePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Workspace"
  objects: {
    AuditLog: Prisma.$AuditLogPayload<ExtArgs>[]
    Invitation: Prisma.$InvitationPayload<ExtArgs>[]
    Membership: Prisma.$MembershipPayload<ExtArgs>[]
    Notification: Prisma.$NotificationPayload<ExtArgs>[]
    Project: Prisma.$ProjectPayload<ExtArgs>[]
    User: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    createdAt: Date
    updatedAt: Date
    description: string | null
    ownerId: string | null
    avatarUrl: string | null
  }, ExtArgs["result"]["workspace"]>
  composites: {}
}

export type WorkspaceGetPayload<S extends boolean | null | undefined | WorkspaceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkspacePayload, S>

export type WorkspaceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkspaceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkspaceCountAggregateInputType | true
  }

export interface WorkspaceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Workspace'], meta: { name: 'Workspace' } }
  /**
   * Find zero or one Workspace that matches the filter.
   * @param {WorkspaceFindUniqueArgs} args - Arguments to find a Workspace
   * @example
   * // Get one Workspace
   * const workspace = await prisma.workspace.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkspaceFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkspaceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Workspace that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkspaceFindUniqueOrThrowArgs} args - Arguments to find a Workspace
   * @example
   * // Get one Workspace
   * const workspace = await prisma.workspace.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkspaceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkspaceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Workspace that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceFindFirstArgs} args - Arguments to find a Workspace
   * @example
   * // Get one Workspace
   * const workspace = await prisma.workspace.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkspaceFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkspaceFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Workspace that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceFindFirstOrThrowArgs} args - Arguments to find a Workspace
   * @example
   * // Get one Workspace
   * const workspace = await prisma.workspace.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkspaceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkspaceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Workspaces that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Workspaces
   * const workspaces = await prisma.workspace.findMany()
   * 
   * // Get first 10 Workspaces
   * const workspaces = await prisma.workspace.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workspaceWithIdOnly = await prisma.workspace.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkspaceFindManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Workspace.
   * @param {WorkspaceCreateArgs} args - Arguments to create a Workspace.
   * @example
   * // Create one Workspace
   * const Workspace = await prisma.workspace.create({
   *   data: {
   *     // ... data to create a Workspace
   *   }
   * })
   * 
   */
  create<T extends WorkspaceCreateArgs>(args: Prisma.SelectSubset<T, WorkspaceCreateArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Workspaces.
   * @param {WorkspaceCreateManyArgs} args - Arguments to create many Workspaces.
   * @example
   * // Create many Workspaces
   * const workspace = await prisma.workspace.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkspaceCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Workspaces and returns the data saved in the database.
   * @param {WorkspaceCreateManyAndReturnArgs} args - Arguments to create many Workspaces.
   * @example
   * // Create many Workspaces
   * const workspace = await prisma.workspace.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Workspaces and only return the `id`
   * const workspaceWithIdOnly = await prisma.workspace.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkspaceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkspaceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Workspace.
   * @param {WorkspaceDeleteArgs} args - Arguments to delete one Workspace.
   * @example
   * // Delete one Workspace
   * const Workspace = await prisma.workspace.delete({
   *   where: {
   *     // ... filter to delete one Workspace
   *   }
   * })
   * 
   */
  delete<T extends WorkspaceDeleteArgs>(args: Prisma.SelectSubset<T, WorkspaceDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Workspace.
   * @param {WorkspaceUpdateArgs} args - Arguments to update one Workspace.
   * @example
   * // Update one Workspace
   * const workspace = await prisma.workspace.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkspaceUpdateArgs>(args: Prisma.SelectSubset<T, WorkspaceUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Workspaces.
   * @param {WorkspaceDeleteManyArgs} args - Arguments to filter Workspaces to delete.
   * @example
   * // Delete a few Workspaces
   * const { count } = await prisma.workspace.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkspaceDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Workspaces.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Workspaces
   * const workspace = await prisma.workspace.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkspaceUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkspaceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Workspaces and returns the data updated in the database.
   * @param {WorkspaceUpdateManyAndReturnArgs} args - Arguments to update many Workspaces.
   * @example
   * // Update many Workspaces
   * const workspace = await prisma.workspace.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Workspaces and only return the `id`
   * const workspaceWithIdOnly = await prisma.workspace.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkspaceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkspaceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Workspace.
   * @param {WorkspaceUpsertArgs} args - Arguments to update or create a Workspace.
   * @example
   * // Update or create a Workspace
   * const workspace = await prisma.workspace.upsert({
   *   create: {
   *     // ... data to create a Workspace
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Workspace we want to update
   *   }
   * })
   */
  upsert<T extends WorkspaceUpsertArgs>(args: Prisma.SelectSubset<T, WorkspaceUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Workspaces.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceCountArgs} args - Arguments to filter Workspaces to count.
   * @example
   * // Count the number of Workspaces
   * const count = await prisma.workspace.count({
   *   where: {
   *     // ... the filter for the Workspaces we want to count
   *   }
   * })
  **/
  count<T extends WorkspaceCountArgs>(
    args?: Prisma.Subset<T, WorkspaceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkspaceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Workspace.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkspaceAggregateArgs>(args: Prisma.Subset<T, WorkspaceAggregateArgs>): Prisma.PrismaPromise<GetWorkspaceAggregateType<T>>

  /**
   * Group by Workspace.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkspaceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkspaceGroupByArgs['orderBy'] }
      : { orderBy?: WorkspaceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkspaceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkspaceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Workspace model
 */
readonly fields: WorkspaceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Workspace.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkspaceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  AuditLog<T extends Prisma.Workspace$AuditLogArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Workspace$AuditLogArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuditLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Invitation<T extends Prisma.Workspace$InvitationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Workspace$InvitationArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InvitationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Membership<T extends Prisma.Workspace$MembershipArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Workspace$MembershipArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MembershipPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Notification<T extends Prisma.Workspace$NotificationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Workspace$NotificationArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Project<T extends Prisma.Workspace$ProjectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Workspace$ProjectArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  User<T extends Prisma.Workspace$UserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Workspace$UserArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Workspace model
 */
export interface WorkspaceFieldRefs {
  readonly id: Prisma.FieldRef<"Workspace", 'Int'>
  readonly name: Prisma.FieldRef<"Workspace", 'String'>
  readonly createdAt: Prisma.FieldRef<"Workspace", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Workspace", 'DateTime'>
  readonly description: Prisma.FieldRef<"Workspace", 'String'>
  readonly ownerId: Prisma.FieldRef<"Workspace", 'String'>
  readonly avatarUrl: Prisma.FieldRef<"Workspace", 'String'>
}
    

// Custom InputTypes
/**
 * Workspace findUnique
 */
export type WorkspaceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * Filter, which Workspace to fetch.
   */
  where: Prisma.WorkspaceWhereUniqueInput
}

/**
 * Workspace findUniqueOrThrow
 */
export type WorkspaceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * Filter, which Workspace to fetch.
   */
  where: Prisma.WorkspaceWhereUniqueInput
}

/**
 * Workspace findFirst
 */
export type WorkspaceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * Filter, which Workspace to fetch.
   */
  where?: Prisma.WorkspaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workspaces to fetch.
   */
  orderBy?: Prisma.WorkspaceOrderByWithRelationInput | Prisma.WorkspaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Workspaces.
   */
  cursor?: Prisma.WorkspaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workspaces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workspaces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workspaces.
   */
  distinct?: Prisma.WorkspaceScalarFieldEnum | Prisma.WorkspaceScalarFieldEnum[]
}

/**
 * Workspace findFirstOrThrow
 */
export type WorkspaceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * Filter, which Workspace to fetch.
   */
  where?: Prisma.WorkspaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workspaces to fetch.
   */
  orderBy?: Prisma.WorkspaceOrderByWithRelationInput | Prisma.WorkspaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Workspaces.
   */
  cursor?: Prisma.WorkspaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workspaces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workspaces.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workspaces.
   */
  distinct?: Prisma.WorkspaceScalarFieldEnum | Prisma.WorkspaceScalarFieldEnum[]
}

/**
 * Workspace findMany
 */
export type WorkspaceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * Filter, which Workspaces to fetch.
   */
  where?: Prisma.WorkspaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workspaces to fetch.
   */
  orderBy?: Prisma.WorkspaceOrderByWithRelationInput | Prisma.WorkspaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Workspaces.
   */
  cursor?: Prisma.WorkspaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workspaces from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workspaces.
   */
  skip?: number
  distinct?: Prisma.WorkspaceScalarFieldEnum | Prisma.WorkspaceScalarFieldEnum[]
}

/**
 * Workspace create
 */
export type WorkspaceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * The data needed to create a Workspace.
   */
  data: Prisma.XOR<Prisma.WorkspaceCreateInput, Prisma.WorkspaceUncheckedCreateInput>
}

/**
 * Workspace createMany
 */
export type WorkspaceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Workspaces.
   */
  data: Prisma.WorkspaceCreateManyInput | Prisma.WorkspaceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Workspace createManyAndReturn
 */
export type WorkspaceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * The data used to create many Workspaces.
   */
  data: Prisma.WorkspaceCreateManyInput | Prisma.WorkspaceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Workspace update
 */
export type WorkspaceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * The data needed to update a Workspace.
   */
  data: Prisma.XOR<Prisma.WorkspaceUpdateInput, Prisma.WorkspaceUncheckedUpdateInput>
  /**
   * Choose, which Workspace to update.
   */
  where: Prisma.WorkspaceWhereUniqueInput
}

/**
 * Workspace updateMany
 */
export type WorkspaceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Workspaces.
   */
  data: Prisma.XOR<Prisma.WorkspaceUpdateManyMutationInput, Prisma.WorkspaceUncheckedUpdateManyInput>
  /**
   * Filter which Workspaces to update
   */
  where?: Prisma.WorkspaceWhereInput
  /**
   * Limit how many Workspaces to update.
   */
  limit?: number
}

/**
 * Workspace updateManyAndReturn
 */
export type WorkspaceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * The data used to update Workspaces.
   */
  data: Prisma.XOR<Prisma.WorkspaceUpdateManyMutationInput, Prisma.WorkspaceUncheckedUpdateManyInput>
  /**
   * Filter which Workspaces to update
   */
  where?: Prisma.WorkspaceWhereInput
  /**
   * Limit how many Workspaces to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Workspace upsert
 */
export type WorkspaceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * The filter to search for the Workspace to update in case it exists.
   */
  where: Prisma.WorkspaceWhereUniqueInput
  /**
   * In case the Workspace found by the `where` argument doesn't exist, create a new Workspace with this data.
   */
  create: Prisma.XOR<Prisma.WorkspaceCreateInput, Prisma.WorkspaceUncheckedCreateInput>
  /**
   * In case the Workspace was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkspaceUpdateInput, Prisma.WorkspaceUncheckedUpdateInput>
}

/**
 * Workspace delete
 */
export type WorkspaceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
  /**
   * Filter which Workspace to delete.
   */
  where: Prisma.WorkspaceWhereUniqueInput
}

/**
 * Workspace deleteMany
 */
export type WorkspaceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Workspaces to delete
   */
  where?: Prisma.WorkspaceWhereInput
  /**
   * Limit how many Workspaces to delete.
   */
  limit?: number
}

/**
 * Workspace.AuditLog
 */
export type Workspace$AuditLogArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuditLog
   */
  select?: Prisma.AuditLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuditLog
   */
  omit?: Prisma.AuditLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuditLogInclude<ExtArgs> | null
  where?: Prisma.AuditLogWhereInput
  orderBy?: Prisma.AuditLogOrderByWithRelationInput | Prisma.AuditLogOrderByWithRelationInput[]
  cursor?: Prisma.AuditLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AuditLogScalarFieldEnum | Prisma.AuditLogScalarFieldEnum[]
}

/**
 * Workspace.Invitation
 */
export type Workspace$InvitationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Invitation
   */
  select?: Prisma.InvitationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Invitation
   */
  omit?: Prisma.InvitationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InvitationInclude<ExtArgs> | null
  where?: Prisma.InvitationWhereInput
  orderBy?: Prisma.InvitationOrderByWithRelationInput | Prisma.InvitationOrderByWithRelationInput[]
  cursor?: Prisma.InvitationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InvitationScalarFieldEnum | Prisma.InvitationScalarFieldEnum[]
}

/**
 * Workspace.Membership
 */
export type Workspace$MembershipArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Membership
   */
  select?: Prisma.MembershipSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Membership
   */
  omit?: Prisma.MembershipOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MembershipInclude<ExtArgs> | null
  where?: Prisma.MembershipWhereInput
  orderBy?: Prisma.MembershipOrderByWithRelationInput | Prisma.MembershipOrderByWithRelationInput[]
  cursor?: Prisma.MembershipWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MembershipScalarFieldEnum | Prisma.MembershipScalarFieldEnum[]
}

/**
 * Workspace.Notification
 */
export type Workspace$NotificationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  where?: Prisma.NotificationWhereInput
  orderBy?: Prisma.NotificationOrderByWithRelationInput | Prisma.NotificationOrderByWithRelationInput[]
  cursor?: Prisma.NotificationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NotificationScalarFieldEnum | Prisma.NotificationScalarFieldEnum[]
}

/**
 * Workspace.Project
 */
export type Workspace$ProjectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  cursor?: Prisma.ProjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Workspace.User
 */
export type Workspace$UserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Workspace without action
 */
export type WorkspaceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workspace
   */
  select?: Prisma.WorkspaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workspace
   */
  omit?: Prisma.WorkspaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceInclude<ExtArgs> | null
}
